spring.application.name=admin
server.servlet.context-path=/admin

server.port=8085

spring.devtools.restart.exclude=static/**,public/**
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# \ub370\uc774\ud130 \uc18c\uc2a4 - MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/security_guard?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&autoReconnection=true&autoReconnection=true
spring.datasource.username=emperor
spring.datasource.password=emperor

#spring.datasource.username=root
#spring.datasource.password=230945
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mybatis \uc124\uc815
# Mybatis \uc124\uc815 \uacbd\ub85c      : ~/resources/mybatis-config.xml
# mybatis.config-location=classpath:mybatis-config.xml

# \uceec\ub7fc\uba85\uc744 \ubcc0\uc218\uba85\uc73c\ub85c \uc790\ub3d9\ub9e4\ud551 :  board_no \u27a1 boardNo
mybatis.configuration.map-underscore-to-camel-case=true
# resultType \uc18d\uc131\uc5d0\uc11c dto \uac1d\uccb4 (\ud328\ud0a4\uc9c0.\ud074\ub798\uc2a4\uba85) \u27a1 (\ud074\ub798\uc2a4\uba85)
mybatis.type-aliases-package=com.safeg.admin.vo

# Mybatis \ub9e4\ud37c \ud30c\uc77c \uacbd\ub85c : ~/\uba54\uc778\ud328\ud0a4\uc9c0/mapper/**Mapper.xml
mybatis.mapper-locations=classpath:/mapper/**/*.xml

# Mybatis TypeHandler \ud328\ud0a4\uc9c0 \uacbd\ub85c
mybatis.type-handlers-package=com.safeg.admin.config

# \uc5c5\ub85c\ub4dc \uacbd\ub85c
# upload.path= /Users/pieck/Documents/upload
upload.path=${UPLOAD_PATH:/Users/pieck/Documents/upload}

# Aligo API Settings
aligo.api.key=2e396nzser8280i9rdo5rvw1s4m5s4ks
aligo.api.userid=23emperor
aligo.api.sender=01038966824


# application.properties
server.error.whitelabel.enabled=true
# Whitelabel Error Page \uc0ac\uc6a9 \uc5ec\ubd80 (\uae30\ubcf8 true)
server.error.include-message=always
# \uc5d0\ub7ec \uba54\uc2dc\uc9c0 \ud56d\uc0c1 \ud3ec\ud568
server.error.include-exception=true
# \uc608\uc678 \ud074\ub798\uc2a4 \ud3ec\ud568
server.error.include-stacktrace=always
# \uc2a4\ud0dd \ud2b8\ub808\uc774\uc2a4 \ud56d\uc0c1 \ud3ec\ud568
server.error.include-binding-errors=always
# \ubc14\uc778\ub529 \uc5d0\ub7ec \ud3ec\ud568

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# server.port=443
# server.ssl.enabled=true
# server.ssl.key-store=classpath:keystore.p12  # \uac00\ube44\uc544\uc5d0\uc11c \ubc1b\uc740 \ud30c\uc77c
# server.ssl.key-store-password=\uc778\uc99d\uc11c\uc554\ud638
# server.ssl.key-store-type=PKCS12

# 1. \ud3ec\ud2b8\ub97c HTTPS \uae30\ubcf8\uc778 443\uc73c\ub85c \ubcc0\uacbd
# server.port=443

# # 2. SSL \uc124\uc815 \ud65c\uc131\ud654
# server.ssl.enabled=true
# # 3. \ud30c\uc77c \uacbd\ub85c \uc9c0\uc815 (resources \ud3f4\ub354 \uae30\uc900)
# server.ssl.key-store=classpath:keystore.p12
# # 4. \uc544\uae4c \uc815\ud55c \ube44\ubc00\ubc88\ud638 \uc785\ub825
# server.ssl.key-store-password=aosqkf12!!
# # 5. \ud615\uc2dd \ubc0f \ubcc4\uce6d \uc9c0\uc815
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=tomcat
encryption.secret-key=mk7W!p9N5v&mR5zQ8xL#u1A4E5tY0iO3
server.forward-headers-strategy=native

logging.level.root=WARN

# \ub0b4 \ud504\ub85c\uc81d\ud2b8(SafeGuard) \uad00\ub828 \ub85c\uadf8\ub294 \uacbd\uace0(WARN) \uc774\uc0c1\ub9cc \ucd9c\ub825
logging.level.com.safeg=WARN

# \uc2a4\ud504\ub9c1 \ub85c\uace0\ub294 \uacc4\uc18d \uaebc\ub450\uae30
spring.main.banner-mode=off